name: sistemakaizendevcompose

services:
  database:
    restart: unless-stopped
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistemakaizendev
    volumes:
      - type: volume
        source: SKDevDbVolume
        target: /var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - type: bind
        source: ..
        target: /workspace
    #command: dotnet watch --non-interactive --no-launch-profile
    command: sleep infinity
    network_mode: service:database

volumes:
  SKDevDbVolume: