name: sistemakaizencompose

services:
  database:
    restart: unless-stopped
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistemakaizen
    volumes:
      - type: volume
        source: sistemakaizendbvolume
        target: /var/lib/postgresql/data
#    ports:
#      - 5432:5432

  backend:
    command: sleep infinity
    tty: true
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - type: bind
        source: ..
        target: /workspace
    network_mode: service:database

  pgadmin:
    restart: unless-stopped
    depends_on:
      - database
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 5050
    network_mode: service:database

volumes:
  sistemakaizendbvolume:
